---
# Ports et services autorisés en entrée
firewall_allowed_tcp_ports:
  - "22"    # SSH
  - "80"    # HTTP
  - "443"   # HTTPS

# Services supplémentaires
firewall_additional_rules: []
  # - chain: INPUT
  #   protocol: tcp
  #   source: 10.0.0.0/8
  #   destination_port: 22
  #   jump: ACCEPT

# Chaînes et leurs politiques par défaut
firewall_chains:
  - name: INPUT
    policy: DROP
  - name: FORWARD
    policy: DROP
  - name: OUTPUT
    policy: ACCEPT