---
- name: Create Portainer volume directory
  file:
    path: /tools/portainer
    state: directory
    mode: '0755'

- name: Pull Portainer image
  docker_image:
    name: portainer/portainer-ce
    source: pull
    force_source: yes

- name: Start Portainer container
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    state: started
    restart_policy: always
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tools/portainer:/data"
